version: "3"
services:
  vue:
    container_name: mywebsite
    build:
      context: .
      dockerfile: ./build/vue/Dockerfile
      args:
        - APPNAME=MyWebsite
    ports:
      - "5173:5173"
    volumes:
      - "./vue/app:/app"
    tty: true
    stdin_open: true
    env_file:
      - secret/vueenv.secret
