version: "3"
services:
  vue:
    container_name: mywebsite_prev
    build:
      context: .
      dockerfile: ./build-prev/vue/Dockerfile
      args:
        - APPNAME=MyWebsite
    ports:
      - "80:80"
    